### ISSUE TITLE
請教設置的問題

### ISSUE THREAD

**Issue by carry0987** [lining91/MessageBoard#1]
大大，請問一下，我在我的服務器上測試的時候，怎麼發都發不出訊息..
https://www.nehscsa.com/test6/login.php

**Comment by lining91** [comment]
不好意思，刚看到，能说详细点吗

**Comment by lining91** [comment]
@carry0987 不好意思，刚看到，能说详细点吗

**Comment by carry0987** [comment]
那個，沒事了，是我搞錯了，我以為是類似消息牆的東西，我另外創建了兩個用戶後，成功發消息了

**Comment by lining91** [comment]
@carry0987 棒
